version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - cd backend
      - chmod +x gradlew
      - ./gradlew clean bootJar -x test

  post_build:
    commands:
      - mkdir -p ../deploy-backend
      - cp build/libs/*.jar ../deploy-backend/app.jar

artifacts:
  files:
    - '**/*'
  base-directory: deploy-backend