server:
  port: 5000

spring:
  datasource:
    url: jdbc:mariadb://awseb-e-ppzmaadqdf-stack-awsebrdsdatabase-37eyl5iugvt0.cbkkm66u0z6l.ap-northeast-2.rds.amazonaws.com:3306/bookdb
    username: admin
    password: sta!0035
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example.bookmanagement: DEBUG